### ISSUE TITLE
SimplenoteListHeight Doesn't Appear To Do Anything

### ISSUE THREAD

**Issue by raisin-loaf** [mrtazz/simplenote.vim#100]
I've got a feeling this is more a case of me not understanding how the feature is supposed to work but the list view doesn't seem to change when I set SimplenoteListHeight. Regardless of the number I pick the list always opens in a full height window. Could you possibly explain what this option is supposed to do please? I thought setting it to something like 20 would reduce the screen real estate given over to the list offering more space for the notes opened in the split.

Thanks for writing such a fantastic plugin. :)

EDIT: Running Vim 8.0 on Debian 9.3

**Comment by atomicules** [comment]
Hi! There isn’t a `SimplenoteListHeight`, but there is a `SimplenoteListSize` that _should_ do what you are expecting (in horizontal or vertical mode).

Off the top of my head I’m guessing it used to be called `SimplenoteListHeight`, but we changed it when it became possible to use a vertical split. Did you find an old doc reference to `SimplenoteListHeight` somewhere?

**Comment by atomicules** [comment]
Ha! Err... you know how you look for something, but just can’t see it... well, I did that yesterday.

I’ll get that fixed. Thank you for pointing that out.

**Comment by raisin-loaf** [comment]
> Ha! Err... you know how you look for something, but just can’t see it... well, I did that yesterday.

Absolutely. That's 80% of my working day. How many times do you I think searched that file before daring to post that? ;)

Thanks again!
