### ISSUE TITLE
Is there notes list update command? 

### ISSUE THREAD

**Issue by traut** [mrtazz/simplenote.vim#102]
I noticed that the list of notes i not updated when new note is created or note list is changed on the server. Is there a command I can trigger manualy to refresh the notes list?

**Comment by atomicules** [comment]
`:SimpleNoteList` will update the list... but it can be slow if lots of notes. I am going to look into caching this soon to speed this up.

**Comment by traut** [comment]
that command will also open new list in the new window 😞

**Comment by atomicules** [comment]
Hmmm... depends how things are setup. The [single window setting](https://github.com/mrtazz/simplenote.vim#single-window-mode) should do what you want.
