### ISSUE TITLE
Authentication stopped working

### ISSUE THREAD

**Issue by m1foley** [mrtazz/simplenote.vim#103]
`Simplenote#authenticate` started raising an exception when I log in. I'm guessing Simplenote changed their API because simplenote.vim hasn't changed in a while, and I've verified my user/pass still works via the Simplenote Mac app and their website. 

The only info I could find from `HTTPError` is `400 BAD REQUEST`.

**Comment by atomicules** [comment]
Weird... I have seen some intermittent issues recently, but none that 
persisted. Just checked now and I am getting a `Login Failed` in 
simplenote.vim and yet doing something direct in simplenote.py worked.

Strange.

**Comment by atomicules** [comment]
This is odd. Will probably need to contact Simplenote/Simperium... wonder if our API token has been revoked?

**Comment by atomicules** [comment]
Boo hiss... 

```< HTTP/1.1 400 BAD REQUEST
< Server: nginx
< Date: Wed, 09 Jan 2019 09:45:39 GMT
< Content-Type: application/json; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Credentials: true
<
* Connection #0 to host auth.simperium.com left intact
rate limited
```

Will have to ask Simplenote/Simperium about it. Rate limiting for auth is... annoying.

For simplenote.vim I could definitely look to cache an auth token.

**Comment by atomicules** [comment]
As a work-around... I could add a setting so we can provide an auth token from elsewhere (the web app) and use that if available.

**Comment by atomicules** [comment]
I'm thinking something like that ^

Although will look to cache a token as well.

**Comment by atomicules** [comment]
Simplenote support had a look and found this:

> It does look like someone was trying to use a pwned user list with that token (unsuccessfully). We made some tweaks to the rate limiting and how it ties to the ip address. This should allow your users to sign in without hitting the limit. Let me know if you still see it happening though!

I have also learnt the tokens have no expiry though so I will work on adding caching asap.

**Comment by louwers** [comment]
Also getting 'Login Failed' with correct login details.

**Comment by atomicules** [comment]
If that's still happening then your only option is obtain a token from elsewhere (i.e the web app) and use it with that branch I've pushed. See the commit comment for how to get that token.

Still working on merging that in and caching a token (which I can do so we can manually edit that "cache" and add a token from elsewhere).

**Comment by atomicules** [comment]
Once I've bumped simplenote.py to handle errors from invalid tokens ^ and then made changes here I think we can close this out.

**Comment by atomicules** [comment]
Closing this out now with: https://github.com/mrtazz/simplenote.vim/commit/c79ca3f982b3cfe547d93e42907f1b1f527ebd82
