### ISSUE TITLE
Missing indicator for pinned status

### ISSUE THREAD

**Issue by m1foley** [mrtazz/simplenote.vim#107]
Simplenote usually prepends a circle to the title of pinned notes. For parity the Vim plugin should have this indicator as well.

Simplenote appears to use images, not characters, to render the circles. The web interface renders them with CSS.

Ideas for implementing this in the Vim plugin:
- Prepend title with *
- Prepend title with a symbol like ⊙ or  ·
- Add a new column next to the tags

**Comment by atomicules** [comment]
We already have this thanks to https://github.com/mrtazz/simplenote.vim/pull/57/

I use that and it works great.
