### ISSUE TITLE
Deleting note doesn't remove note from list

### ISSUE THREAD

**Issue by m1foley** [mrtazz/simplenote.vim#62]
Deleting a note (`:Simplenote -D`) should also remove it from the list buffer. It currently leaves it there after deleting, and when I attempt to view the deleted note it leads to an error:

```
Error detected while processing function <SNR>74_GetNoteToCurrentBuffer:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 276, in display_note_in_scratch_buffer
TypeError: sequence index must be integer, not 'str'
```

**Comment by atomicules** [comment]
I agree. I'm working on a tricky (for me) issue/pull request on 
simplenote.py at the moment, but when I've finished with that I'll 
take a look at this issue. So could be a couple of weeks until I get 
around to it.

**Comment by m1foley** [comment]
Thanks. This is a really sweet plugin! :+1:

**Comment by atomicules** [comment]
Just pushed a fix for this. Forgot to say in the commit message that 
as well as removing the entry from the list index buffer we are now 
also using `:bdelete` to remove the buffer of the deleted note
- previously it was just "closed" with `:quit`
