### ISSUE TITLE
Use prefixed commands rather than flags

### ISSUE THREAD

**Issue by m1foley** [mrtazz/simplenote.vim#63]
[fugitive.vim](https://github.com/tpope/vim-fugitive) has easy-to-remember commands like `:Gstatus`, `:Gcommit` and `:Gremove`. If simplenote.vim prefixed all commands with `:Sn` (for example) I wouldn't have to call `:help` to remember which flag I want. The commands would be easy to remember, and if I forgot I could simply type `:Sn` and autocomplete to `:Snlist`, `:Snremove`, `:Sntag` etc.

**Comment by m1foley** [comment]
I can give this a shot myself when I have time, if you agree that this is worth doing.

**Comment by m1foley** [comment]
Alternate prefixes would be `:Simplenote` and `:S`. I assume the former is too long, and the latter doesn't have good autocompletion.

**Comment by atomicules** [comment]
Hi. It's certainly worth thinking about and I'm not against it.  
Although I think which approach is better pretty much boils down to 
user preference. The only potential downside I see is being overrun 
with autocomplete commands (I do find myself overrun with ones 
beginning with "G"), but I don't currently have many beginning with 
"S". 

Perhaps we could keep both approaches? I'll have more of a think about 
it tomorrow. 

Certainly feel free to have a go at implementing it. That way we can 
see if there are any downsides, etc.

**Comment by atomicules** [comment]
Closed by 49ca7787af7e28975eab32265be8194264c15613
