### ISSUE TITLE
Can't install via Vundle

### ISSUE THREAD

**Issue by alexanderklein** [mrtazz/simplenote.vim#65]
Hello,

I installed the plugin via Vundle and get the following error message when I try to execute any Simplenote command:

Error detected while processing function simplenote#SimpleNote:
line   45:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.

I also ran git submodule update --init (also I understood that this should not be required when the plugin is being installed via Vundle) but that doesn't solve the issue.

Any advise would be appreciated.

Many thanks, Alex

**Comment by atomicules** [comment]
Hi, thanks for the report, I shall take a look. This is odd because I use Vundle, but I probably haven't updated Vundle itself in awhile.

**Comment by atomicules** [comment]
Hi, sorry for it taking a couple of days to get back to you. I just started from a fresh `~/.vim` directory and a brand new Vundle install and installing Simplenote.vim worked fine, pulling in the submodule automatically.

What platform are you using? Version of Python? What version of python is vim linked against (see output of `:version` in Vim)?

**Comment by alexanderklein** [comment]
Hi, I find that you were coming back very quickly :-) Thanks for that.

I'm on Mac OS X 10.10.4

I think you are looking for this output:

Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FO
RTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -F/usr/local/Frameworks
-Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-
2level/CORE -lperl -F/usr/local/Cellar/python/2.7.10/Frameworks -framework Python   -lruby.2.2.0 -lobjc -L/usr/local/Cellar/ruby/2.2.2/lib

So, it is python 2.7.10 installed via Homebrew

Many thanks again. I will also keep on trying.

**Comment by atomicules** [comment]
Hi,

I don't know what the problem is yet. I don't think it is anything 
specific to Simplenote.vim though. I think it is something to do with 
how Vim and Python are linked, but I can't tell what - the version 
information from Vim seems like it should be ok.

I'll do some research and reading around and let you know if I 
find anything.

**Comment by alexanderklein** [comment]
Thanks a lot. It seems to be very specific to my system :-( 
I will do some research too.

Thanks again.

**Comment by alexanderklein** [comment]
Okay - I found this discussion:
https://github.com/editorconfig/editorconfig/issues/178

And re-installing vim via homebrew solved the problem. Odd. So, it's indeed not a simplenote specific problem. Sorry for bothering you but now you know at least what to answer if other users experience this homebrew issue with your pugin first :-)

Are you going to close this issue or should I?

Again, thanks for your swift replies.

**Comment by alecthegeek** [comment]
I've just verified this behaviour. Running `brew uninstall --force macvim` followed by `brew install macvim` fixed the problem

**Comment by atomicules** [comment]
Thanks for updating here Alexander and thanks for the confirmation 
Alec. Feel free to close out the issue.

**Comment by alexanderklein** [comment]
Issue resides in homebrew rather than in the simplenote plug-in.
Re-installing vim / macvim after a python upgrade fixes the problem for the time being.
