### ISSUE TITLE
Customize note opening behavior

### ISSUE THREAD

**Issue by apazzolini** [mrtazz/simplenote.vim#70]
Hey, thanks for the great plugin! I was hoping it would be easy to add the ability to make the note open to the right of the scratch window instead of on the left when using vertical split. Additionally, opening a second note causes a third split to appear - it would be nice to customize that to only allow one open note at a time.

Thanks!

**Comment by atomicules** [comment]
> add the ability to make the note open to the right of the scratch window instead of on the left when using vertical split

Do you mean opening a note from the list index? If so then the direction of opening should be determined in your `.vimrc` and is unrelated to Simplenote.vim. I have the following in my `.vimrc`:

    set splitbelow
    set splitright

>  Additionally, opening a second note causes a third split to appear - it would be nice to customize that to only allow one open note at a time

I could think about that.

**Comment by apazzolini** [comment]
Oh cool, didn't know about those flags, that takes care of the first one, thanks!

My rationale for the second one is I have an instance of vim permanently open for notes usage. My ideal workflow would be to have the list scratch permanently open and use it to switch between notes (similar to the simplenote web interface).

**Comment by atomicules** [comment]
Yeah, it makes sense and is a good idea when you put it like that. 
I'll not get right to it, but I will start thinking about it.

**Comment by atomicules** [comment]
Hi,

I've just pushed this functionality to a new branch. Please read the 
commit comments because the behaviour isn't (and can't be) perfect 
because of the way Vim behaves and treats windows and buffers.

I'd appreciate it if you could then test it and see if it works as 
you'd expect before I think about merging this in.

I've tested the functionality quite a bit in developing it so I'm 
pretty happy with how it works, but I'm not too happy with the code
as I feel it is a bit messy (although I'm not sure if I'll be able to 
simplify it).

**Comment by apazzolini** [comment]
Hey dude, thanks for getting to this! The functionality you implemented is exactly what I hoped it would be - I did some testing and everything worked perfectly. Furthermore, I think the behavior that happens when you manually open a split is a feature, not a bug.

- Opening different notes in the same window (obviously)
- Triggering the current note to open again (refreshing with the latest from Simplenote)
- Creating a new split causes old note to remain open while new notes open in new split (this can be handy if I want to have multiple notes open at the same time)
  - Both notes still update Simplenote properly
  - Closing the middle note allows the initial split to regain control

Thank you!

**Comment by atomicules** [comment]
Wow, thanks for reviewing so quick. I still want to wait a little 
while before merging in just to see if there is anyway I can 
simplify all the if statements I've ended up with.

**Comment by apazzolini** [comment]
Yup, no worries, least I could do for functionality I requested haha.

And sounds good, I can certainly just keep using the branch in the meantime.

**Comment by atomicules** [comment]
Couldn't think of anyway to improve this so I've merged it in as is
