### ISSUE TITLE
Reloading a note that's open in the buffer

### ISSUE THREAD

**Issue by blueberrycake** [mrtazz/simplenote.vim#73]
Is there a command to reload a note that's already open in the buffer, other than reopening the list of notes and selecting the note again? If not, then this feature would be a convenient addition for those of us who are frequently modifying our notes from multiple devices throughout the day.

**Comment by atomicules** [comment]
Good idea. I'll have a think about this. Really this is how `:Simplenote -u` should behave anyway (it should merge in remote changes).

**Comment by atomicules** [comment]
There you go, that's v1 out the door so closing this out

**Comment by atomicules** [comment]
Whoops, that comment was for another, albeit related, issue.

`:Simplenote -u` now updates the current note and merges in remote changes (so you can also use it as a refresh).
