### ISSUE TITLE
Buffer names - Feature suggestion

### ISSUE THREAD

**Issue by blueberrycake** [mrtazz/simplenote.vim#75]
It looks like the notekey is used as the name of the buffer, which is ok if you only have one note open, but if you open several notes, and try to switch buffers, it becomes next to impossible to determine which note is which, since the list of buffer names becomes unreadable.

I assume that you are using notekey as buffer name so that you can properly reference the note when its updated. Assuming Vim doesnt have a facility for hidden variables that can be associated with a buffer, perhaps the names of the buffer can be set to something like "NOTE_NAME - [NOTEKEY]", that way the buffer names become readable, and when a note needs to be updated, you can just parse out the Notekey out of the buffer name.

**Comment by atomicules** [comment]
Hi. Yeah, it would be nice to have better titles than the note key. 
I'm sure this has come up before, but I can't find anything right now 
in the closed issues so perhaps I've seen something before in 
someone's fork awhile back.

I have a look into this and a think about it.

Thanks.

**Comment by atomicules** [comment]
Had another dig through the past issues, commits and network and I can't find anything although I swear I did see a proposal once for something similar to what you are proposing. Adding to my todo list, but I'll look at #73 first.

**Comment by atomicules** [comment]
Added a working solution for this to a separate branch for now. Just having a go at seeing if I can remove the need for having the keys/ids in the buffer names at all. If I can't figure it out I'll merge this into master.

**Comment by atomicules** [comment]
Should have thought about this and noticed before now: It's no longer possible to have two notes with the same first line (title) open because Vim won't let you have multiple buffers of the same name. This is annoying. Will probably have to append key to title.
