### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by m1foley** [mrtazz/simplenote.vim#76]
[Semantic Versioning](http://semver.org/) is becoming the standard for releasing software. Since Simplenote.vim has been in production for a while now, I suggest setting the version to 1.0.0.

**Comment by atomicules** [comment]
Yeah, I've been thinking about doing that for awhile. I think I'll try 
to get #73 closed out and call it 1.0.0.

On a related note: I could do with doing the same to simplenote.py. 
And since simplenote.vim uses that, I should really go do that first.

**Comment by atomicules** [comment]
@m1foley I've released simplenote.py at version 1 and I've created a version 1 milestone here for simplenote.vim for everything I want to complete.

**Comment by atomicules** [comment]
There you go, that's v1 out the door so closing this out

**Comment by m1foley** [comment]
:tada:
