### ISSUE TITLE
Simplenote: Plugin needs vim to be compiled with python support.

### ISSUE THREAD

**Issue by himnsuk** [mrtazz/simplenote.vim#82]
Hi
 I am using vim in console. 
 I faced this issue when fetching notes from server.
 I have install ubuntu 16.04, and python 2.7.11
 Couldn't able to figure out the issue.

**Comment by atomicules** [comment]
Hi. What is the output from `:version` in Vim?

For example, you should see "+python" if Vim is built with python 
support and the Linking information at the bottom should show which 
python it is linked to.

**Comment by himnsuk** [comment]
Hi @atomicules ,
I checked :version in the vim. It is showing +python3.

**Comment by atomicules** [comment]
Ok, at the moment simplenote.vim requires that Vim is built with 
python 2 support (+python). The underlying simplenote.py supports 2 
and 3 and I plan to make simplenote.vim python 3 compatible as well, 
but haven't started work on it yet.

Keep an eye on issue #71

**Comment by himnsuk** [comment]
Okay, I'll check regularly for fix.
Thanks for quick reply :+1:

**Comment by atomicules** [comment]
Closing this issue out. I have started making progress on python 3 changes required under the other issue. Hopefully won't be too long until I have it 2/3 compatible.
