### ISSUE TITLE
Error: Unable to connect to server.

### ISSUE THREAD

**Issue by khimanshu11** [mrtazz/simplenote.vim#90]
When i am trying to use command "Simplenote -l" its giving this error.

**Comment by atomicules** [comment]
Any proxy/firewall issues?

Are you able to logon using [simplenote.py](https://github.com/mrtazz/simplenote.py)?

**Comment by skegel13** [comment]
I am also having this issue. I haven't tried simplenote.py, but I have the Linux Simplenote app and it appears that it is not connecting either (doesn't show all my notes). So I am thinking it may be a server issue with Simplenote.

**Comment by atomicules** [comment]
Closing this out as I don't think there is anything I can do here to help.
