### ISSUE TITLE
slow SimplenoteList?

### ISSUE THREAD

**Issue by jtoy** [mrtazz/simplenote.vim#96]
love the plugin, starting to use it daily.  Is there a way to cache the notes? Every time  I start vim I go to run SimplenoteList and it takes 15 seconds before I can see the list. I have 170 lists, On mac, I can edit as soon as I open the app.

**Comment by atomicules** [comment]
Hi,

this is why I tend to date limit my list a lot. I.e. I'm always using 
something like ``:SimplenoteList 2017-02-01`

Issue #18 has been there forever and my thoughts are much the same: 
I.e conflicted. It would be nice, but I think it'd end up not being 
Simplenote.vim.

**Comment by atomicules** [comment]
This is now (in my mind) a much more legit issue because with the switch to Simperium we lose the use of `since`. So having to fetch all notes is slow and is going to bug me. So need to figure out a better way to do this.
