### ISSUE TITLE
"tags" sort order actually sorts reverse alphabetically by first tag, not by tag existence

### ISSUE THREAD

**Issue by Viqsi** [mrtazz/simplenote.vim#97]
When including "tags" as a sort key in SimplenoteSortOrder, instead of strictly going by whether or not tags exist (as the documentation says it will), it actually seems to sort in a inverse alphabetical order keyed on the first tag listed ('z' through 'a' followed by 'Z' through 'A'). This can lead to unexpected behavior when changing SimplenoteSortOrder.

If one was going strictly by "tag existence", then the expected behavior of SimplenoteSortOrder="pinned,tags,modifydate" would have notes listed in this order:
* pinned and tagged by modifydate
* pinned and untagged by modifydate
* unpinned and tagged by modifydate
* unpinned and untagged by modifydate

Instead, what one gets is:
* pinned by inverse first tag name then by modifydate
* unpinned by inverse first tag name then by modifydate
* unpinned and untagged by modifydate

If this is intended behavior, at the least the documentation ought to be updated. Personally, tho, i'd prefer this functionality do what the docs say. ;)

**Comment by atomicules** [comment]
Interesting, not read through this enough yet, but I thought it reminding me of something: https://github.com/mrtazz/simplenote.vim/issues/95

**Comment by atomicules** [comment]
And less than a year later!
