### ISSUE TITLE
Certain characters now always displayed as HTML entities

### ISSUE THREAD

**Issue by pixelheresy** [mrtazz/simplenote.vim#99]
Following some apparent server updates last week, it looks like certain characters always come back as entitles: `&amp;`,`&gt;`, and `&lt;` etc. Even if you save the buffer, the next load or update converts. Most likely happens on the server, but should be (like in the SimpleNote web and app clients) masked.

This is problematic both for Markdown formatting (> means something in md) and perhaps as well for those who need to put entities in their notes: `&amp;amp;` looks insane.

If the common entities could be shown in the buffer as the standard character, it would be much more usable.

**Comment by atomicules** [comment]
However... if you set the filetype as markdown it looks like it behaves. Will try to look into this and figure out what they've changed.

**Comment by pixelheresy** [comment]
Not sure which markdown plugin you have, but I automatically flag all as markdown and it still looks like crap and shows entities as the markup code. Using vim-markdown and believe it is up to date.

**Comment by pixelheresy** [comment]
Strange. If I have the buffer open and update it externally, and then `:SimplenoteUpdate` it seems to be correct, but if I close VIM and open up everything without the buffer being open, it is all madness again... Just FYI.

**Comment by atomicules** [comment]
[Fix for this in Simplenote.py](https://github.com/mrtazz/simplenote.py/commit/0c37fb413d26fda1f7c35c25c1195e6950dcbb27). Although I've written a test for it I've not actually done extensive testing of it yet. I'm going to do a bit more testing, then do a new release of Simplenote.py and then a new release of Simplenote.vim.

_I really don't have a lot of spare time anymore hence why I'm much less active than I used to be here_

**Comment by atomicules** [comment]
I've bumped the simplenote.py version with the fix. Tomorrow I'll do the simplenote.vim one (hopefully).

**Comment by pixelheresy** [comment]
Excellent! Thanks! Talked with someone in support from SimpleNote and they were unhelpful, mostly due to the fact that it wasn't happening *in* their app or web client...

**Comment by atomicules** [comment]
That auto-closed with that commit ^. _Should_ all be sorted now.
